#!/bin/bash

tools=${JAVA_HOME}/lib/tools.jar
if [ -f ${tools} ]; then
	java -cp target/tjconsole-1.5-SNAPSHOT-all.jar:${tools} org.jsoftware.tjconsole.TJConsole $*
	exitCode=$?
	echo Exit code ${exitCode}
	exit ${exitCode}
else 
	echo Cannot find ${tools}
	exit 22
fi

